### ISSUE TITLE
Request for English version or how to edit original

### ISSUE THREAD

**Issue by GenTxt** [nevmenandr/word2vec-russian-novels#1]
Hello:

Thanks for posting this repo. I have your original Russian word2novel.py running 100% with the ruwikiruscorpora. 

Unfortunately I don't speak/read Russian I was wondering if you could post an English version that runs with GoogleNews-vectors-negative300.bin.gz or similar English model?

I've hacked my way through your script by changing all Russian characters to English but it only outputs the original English files to the "books_after" folder.

Thanks

**Comment by nevmenandr** [comment]
That sounds senseless. The point of this script is to handle Russian inflection. English has no such a rich inflection and it is much more simple to make something like that in English. There is no need to use my script.
BTW you can find the analogue for English [here](https://github.com/arnicas/word2vec-pride-vis). I have no idea why you didn't find it yet :)

**Comment by GenTxt** [comment]
I was aware of the English web version but it didn't suit my needs  :)
What I like about your version is the simple "books before" ---> "books after" processing chain without all the distracting web graphics of the English version.

Not so senseless to me. :)

Non-isssue closed
